#!/usr/bin/env python3
import rospy
import numpy as np

from std_msgs.msg import Int8,Float64
from sensor_msgs.msg import Joy 
from lunabot_msgs.msg import Actuation
from lunabot_msgs.msg import Drivetrain 

class ManualController:
    '''ManualController
    Implements joystick control of lunabotics robot
    '''

    def __init__(self):
        self.subsystems = ['drivetrain', 'actuation', 'excavation', 'deposition']
        self.curr_subsystem = 'drivetrain'

        self._joy_sub = rospy.Subscriber('joy', Joy, self.joy_cb);
        self._drivetrain_pub = rospy.Publisher('cmd_vel', Drivetrain, queue_size=100);
        self._excavation_pub = rospy.Publisher('excavation', Float64, queue_size=100);
        self._deposition_pub = rospy.Publisher('deposition', Int8, queue_size=100);
        self._actuation_pub = rospy.Publisher('actuation', Actuation, queue_size=100);

        self._exc_latch_val = 0.0
        self._excavation_latch = False

    def joy_cb(self, joy):
        if joy.buttons[1]: # 'B' button -- switches the active subsystem
            self.stop()
            #rospy.logerr("STOPPED")
        else:
            self.main_cb(joy)
        

    def constrain(self,joy_in):
        return np.int8(min(joy_in * 128,127))
    
    def main_cb(self, joy):
        # Joysticks
        drive_msg = Drivetrain()
        drive_msg.left = self.constrain(joy.axes[1] * 0.5)
        drive_msg.right = self.constrain(joy.axes[4] * 0.5)
        self._drivetrain_pub.publish(drive_msg)

        actuation_msg = Actuation()

        # up/down arrows 
        actuation_msg.lead_screw = int(joy.axes[7])

        # left/right bumpers 
        actuation_msg.angle = int(joy.buttons[4] - joy.buttons[5]) * 127
        self._actuation_pub.publish(actuation_msg)


        # left/right arrows 
        deposition_msg = Int8()
        deposition_msg.data = int(joy.axes[6])
        self._deposition_pub.publish(deposition_msg)

        # Triggers
        excavation_msg = Float64()
        excavation_msg.data = (joy.axes[2] - joy.axes[5]) / 2

        # latch excavation
        if joy.buttons[3] == 1:
            self._excavation_latch = not self._excavation_latch
            self._exc_latch_val = excavation_msg.data
        
        if not self._excavation_latch:
            self._excavation_pub.publish(excavation_msg)
        
    def loop(self):
        if self._excavation_latch:
            self._excavation_pub.publish(self._exc_latch_val)

    def stop(self):
        cmd_vel_stop = Drivetrain()
        cmd_vel_stop.left = 0
        cmd_vel_stop.right = 0
        actuation_stop = Actuation()
        actuation_stop.lead_screw = 0
        actuation_stop.angle = 0
        excavation_stop = Float64()
        excavation_stop.data = 0
        deposition_stop = Int8()
        deposition_stop.data = 0

        self._exc_latch_val = 0
        self._excavation_latch = False

        self._actuation_pub.publish(actuation_stop)
        self._excavation_pub.publish(excavation_stop)
        self._deposition_pub.publish(deposition_stop)

if __name__ == '__main__':
    rospy.init_node('manual_controller_node')

    vs = ManualController()

    r = rospy.Rate(10)

    while not rospy.is_shutdown():
        vs.loop()
        r.sleep()

    rospy.spin()