#!/usr/bin/env python3
import rospy
import numpy as np

from std_msgs.msg import Int8,Float32,UInt8
from sensor_msgs.msg import Joy 
from lunabot_msgs.msg import Actuation
from lunabot_msgs.msg import Drivetrain 
from enum import Enum

class DepState(Enum):
    STORED = 0,
    FULL_EXT = 1,
    CNT = 2,
    STOPPED = 3

class BinState(Enum):
    EMPTY = 0,
    FILLING = 1,
    FULL = 2,

class ExcState(Enum):
    NOMINAL= 0,
    OVERCURRENT = 1,

class LinActState(Enum):
    STORED = -1,
    DRIVING = 0,
    FULL_EXT = 1, 
    CNT = 2,
    STOPPED = 3

class LeadScrewState(Enum):
    STORED = 0,
    FULL_EXT = 1,
    CNT = 2,
    STOPPED = 2,

class ManualController:
    '''ManualController
    Implements joystick control of lunabotics robot
    '''

    def __init__(self):
        self.subsystems = ['drivetrain', 'actuation', 'excavation', 'deposition']
        self.curr_subsystem = 'drivetrain'

        dep_topic = rospy.get_param('deposition_setp_topic')
        lin_act_topic = rospy.get_param('lin_act_setp_topic')
        lead_screw_topic = rospy.get_param('lead_screw_setp_topic')

        self._joy_sub = rospy.Subscriber('joy', Joy, self.joy_cb);
        self._drivetrain_pub = rospy.Publisher('cmd_vel', Drivetrain, queue_size=100);
        self._excavation_pub = rospy.Publisher('excavation', Float32, queue_size=100);
        self._deposition_pub = rospy.Publisher(dep_topic, UInt8, queue_size=100);
        self._lin_act_pub = rospy.Publisher(lin_act_topic, UInt8, queue_size=100);
        self._lead_screw_pub = rospy.Publisher(lead_screw_topic, UInt8, queue_size=100);

    def joy_cb(self, joy):
        if joy.buttons[1]: # 'B' button -- switches the active subsystem
            self.stop()
            rospy.logerr("STOPPED")
            return
        else:
            self.main_cb(joy)
    
    def main_cb(self, joy):
        # Joysticks
        drive_msg = Drivetrain()
        drive_msg.left = joy.axes[1]
        drive_msg.right = joy.axes[4]
        self._drivetrain_pub.publish(drive_msg)

        lead_screw_msg = UInt8()
        # up/down arrows 
        ctrl = int(joy.axes[7])
        if ctrl > 0:
            ctrl = LeadScrewState.FULL_EXT 
        elif ctrl < 0:
            ctrl = LeadScrewState.STORED
        else:
            ctrl = LeadScrewState.STOPPED
        lead_screw_msg.data = ctrl 
        self._lead_screw_pub.publish(lin_act_msg)

        # left/right bumpers 
        lin_act_msg = UInt8()
        ctrl = int(joy.buttons[4] - joy.buttons[5])
        if ctrl > 0:
            ctrl = LinActState.DRIVING 
        elif ctrl < 0:
            ctrl = LinActState.FULL_EXT
        else:
            ctrl = LinActState.STOPPED
        lin_act_msg.data = ctrl 
        self._lin_act_pub.publish(lin_act_msg)

        # Triggers
        excavation_msg = Float32()
        excavation_msg.data = joy.axes[2] - joy.axes[5]
        self._excavation_pub.publish(excavation_msg)

        # left/right arrows 
        deposition_msg = UInt8()

        ctrl = int(joy.axes[6])

        if ctrl > 0:
            ctrl = DepState.FULL_EXT 
        elif ctrl < 0:
            ctrl = DepState.STORED
        else:
            ctrl = DepState.STOPPED
        deposition_msg.data = ctrl 
        self._deposition_pub.publish(deposition_msg)

    def stop(self):
        cmd_vel_stop = Drivetrain()
        cmd_vel_stop.left = 0
        cmd_vel_stop.right = 0
        actuation_stop = Actuation()
        actuation_stop.lead_screw = 0
        actuation_stop.angle = 0
        excavation_stop = Float32()
        excavation_stop.data = 0
        deposition_stop = Int8()
        deposition_stop.data = 0

        self._drivetrain_pub.publish(cmd_vel_stop)
        self._actuation_pub.publish(actuation_stop)
        self._excavation_pub.publish(excavation_stop)
        self._deposition_pub.publish(deposition_stop)

if __name__ == '__main__':
    rospy.init_node('manual_controller_node')

    vs = ManualController()
    rospy.spin()
