#!/usr/bin/env python3
import rospy
from std_msgs.msg import Bool, Int32
from pynput.keyboard import Key, Listener

class Pause:
    def __init__(self):
        rospy.init_node('pause_node')
        self.start_pub = rospy.Publisher('simulate', Bool, queue_size=1)
        self.left_pub = rospy.Publisher('left_vel', Int32, queue_size=1)
        self.right_pub = rospy.Publisher('right_vel', Int32, queue_size=1)
        self.bool = True
        self.listener()
    
    def on_press(self, key):
        if(key == Key.space):
            self.bool = not self.bool
            self.start_pub.publish(self.bool)
        else:
            self.left_pub.publish(1)
            self.right_pub.publish(1)
    
    def on_release(self, key):
        pass

    def listener(self):
        with Listener(
            on_press=self.on_press,
            on_release=self.on_release
            ) as listener:
            listener.join()

Pause()