/*:
  apriltag:                 # node name
    ros__parameters:
      image_transport: raw  # image format: "raw" or "compressed"
      family: 36h11         # tag family name: 16h5, 25h9, 36h11
      size: .1905             # default tag edge size in meter
  
  # (optional) list of tags
    # If defined, 'frames' and 'sizes' must have the same length as 'ids'.
      tag: # 368 for sim, 126 IRL
        ids:    [126, 173, 301, 482, 421, 476]         # tag IDs for which to publish transform 
        frames: ["main_deposition", "main_deposition_small", "tag36h11:301", "tag36h11:482", "tag36h11:421", "tag36h11:476"]   # frame names
        sizes:  [0.09603, 0.02, 0.145, 0.145, 0.4375, 0.4375]     # tag-specific edge size, overrides the default 'size'
/mini/*:
  apriltag:                 # node name
    ros__parameters:
      image_transport: raw  # image format: "raw" or "compressed"
      family: 36h11         # tag family name: 16h5, 25h9, 36h11
      size: .1905             # default tag edge size in meter
  
  # (optional) list of tags
    # If defined, 'frames' and 'sizes' must have the same length as 'ids'.
      tag: # 368 for sim, 126 IRL
        ids:    [126, 173, 301, 482, 421, 476]         # tag IDs for which to publish transform
        frames: ["main_deposition", "main_deposition_small", "tag36h11:401", "tag36h11:582", "tag36h11:521", "tag36h11:576"]   # frame names
        sizes:  [0.09603, 0.02, 0.145, 0.145, 0.4375, 0.4375]     # tag-specific edge size, overrides the default 'size'
