rollout_count: 50
top_rollouts: 15
iterations: 10
w_linear: 2.0
w_angular: 2.0
w_waypoint_pos: 20.0
w_waypoint_rot: 10.0
w_occupied: 100.0
w_accel: 1.0
horizon_length: 10
frequency: 30
min_distance_threshold: 0.3
min_angle_threshold: 0.3
velocity_limits:
  linear: [-0.3, 0.3]
  angular: [-0.5, 0.5]
