point_to_point_node:
  ros__parameters:
    frequency: 60.0
    angular:
      p: 5.0
      i: 0.0
      d: 0.0
      max_speed: 60.0
      tolerance: 10.0
    linear:
      p: 3.0
      i: 0.0
      d: 0.0
      max_speed: 0.3
      tolerance: 0.2

mini:
  point_to_point_node:
    ros__parameters:
      frequency: 60.0
      angular:
        p: 5.0
        i: 0.0
        d: 0.0
        max_speed: 60.0
        tolerance: 10.0
      linear:
        p: 3.0
        i: 0.0
        d: 0.0
        max_speed: 0.3
        tolerance: 0.2
