controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

mini:
  controller_manager:
    ros__parameters:
      update_rate: 100  # Hz

      velocity_controller:
        type: velocity_controllers/JointGroupVelocityController

# This makes the controller spawner mad, but it doesn't actually break things
velocity_controller:
  ros__parameters:
    joints:
      - left_front_rev
      - left_back_rev
      - right_front_rev
      - right_back_rev

mini:
  velocity_controller:
    ros__parameters:
      joints:
        - left_front_rev
        - left_back_rev
        - right_front_rev
        - right_back_rev
