global_costmap:
  global_costmap:
    ros__parameters: 
      height: 5
      width: 5
      publish_frequency: 1.0
      update_frequency: 1.0
      always_send_full_costmap: true
      robot_radius: 0.4
      plugins: ["static_layer","denoise_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
      denoise_layer:
        plugin: "nav2_costmap_2d::DenoiseLayer"
        enabled: true
        minimal_group_size: 3
        group_connectivity_type: 8 # 4 is adjacent, 8 includes diagonals
        footprint_clearing_enabled: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 1.5
        cost_scaling_factor: 6.0
        inflate_unknown: true  # should treat unknown as obstacles (maybe change init values)
        inflate_around_unknown: true
        footprint_clearing_enabled: true
      global_frame: "map"
      robot_base_frame: "base_link"

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "SThetaStarPlanner"
      remapping_cost_change_percent: 0.01



controller_server:
  ros__parameters:
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      max_linear_vel: 0.5
      min_linear_vel: -0.5
      max_angular_vel: 2.5
      min_angular_vel: -2.5
      max_linear_accel: 2.5
      max_linear_decel: -2.5
      max_angular_accel: 3.2
      max_angular_decel: -3.2
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 1.8
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.05
      approach_velocity_scaling_dist: 0.6
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      use_fixed_curvature_lookahead: false
      curvature_lookahead_dist: 0.25
      use_cost_regulated_linear_velocity_scaling: false
      cost_scaling_dist: 0.3
      cost_scaling_gain: 1.0
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.25
      use_rotate_to_heading: true
      allow_reversing: false
      rotate_to_heading_min_angle: 0.785
      min_distance_to_obstacle: 0.0
      use_dynamic_window: false
      allow_obstacle_checking_beyond_goal: false

bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map   