# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RobotMsgs.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RobotMsgs.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fRobotMsgs.proto\"\xb7\x02\n\x0cRobotSensors\x12\x16\n\x0e\x61\x63t_right_curr\x18\x01 \x01(\x02\x12\x10\n\x08\x64\x65p_curr\x18\x02 \x01(\x02\x12\x10\n\x08\x65xc_curr\x18\x03 \x01(\x02\x12\x17\n\x0f\x64rive_left_curr\x18\x04 \x01(\x02\x12\x18\n\x10\x64rive_right_curr\x18\x05 \x01(\x02\x12\x19\n\x11\x64rive_left_torque\x18\x06 \x01(\x02\x12\x1a\n\x12\x64rive_right_torque\x18\x07 \x01(\x02\x12\x12\n\nexc_torque\x18\x08 \x01(\x02\x12\x16\n\x0e\x64rive_left_vel\x18\t \x01(\x02\x12\x17\n\x0f\x64rive_right_vel\x18\n \x01(\x02\x12\x0f\n\x07\x65xc_vel\x18\x0b \x01(\x02\x12\x14\n\x0c\x61\x63t_left_pos\x18\x0c \x01(\x03\x12\x15\n\ract_right_pos\x18\r \x01(\x03\"\x93\x01\n\x0bRobotEffort\x12\x0f\n\x07lin_act\x18\x01 \x01(\x11\x12\x12\n\nleft_drive\x18\x02 \x01(\x11\x12\x13\n\x0bright_drive\x18\x03 \x01(\x11\x12\x10\n\x08\x65xcavate\x18\x04 \x01(\x11\x12\x0f\n\x07\x64\x65posit\x18\x05 \x01(\x11\x12\x14\n\x0cshould_reset\x18\x06 \x01(\x08\x12\x11\n\tled_color\x18\x07 \x01(\x11\x62\x06proto3'
)




_ROBOTSENSORS = _descriptor.Descriptor(
  name='RobotSensors',
  full_name='RobotSensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='act_right_curr', full_name='RobotSensors.act_right_curr', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dep_curr', full_name='RobotSensors.dep_curr', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exc_curr', full_name='RobotSensors.exc_curr', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drive_left_curr', full_name='RobotSensors.drive_left_curr', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drive_right_curr', full_name='RobotSensors.drive_right_curr', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drive_left_torque', full_name='RobotSensors.drive_left_torque', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drive_right_torque', full_name='RobotSensors.drive_right_torque', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exc_torque', full_name='RobotSensors.exc_torque', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drive_left_vel', full_name='RobotSensors.drive_left_vel', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drive_right_vel', full_name='RobotSensors.drive_right_vel', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exc_vel', full_name='RobotSensors.exc_vel', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='act_left_pos', full_name='RobotSensors.act_left_pos', index=11,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='act_right_pos', full_name='RobotSensors.act_right_pos', index=12,
      number=13, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=331,
)


_ROBOTEFFORT = _descriptor.Descriptor(
  name='RobotEffort',
  full_name='RobotEffort',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lin_act', full_name='RobotEffort.lin_act', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='left_drive', full_name='RobotEffort.left_drive', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right_drive', full_name='RobotEffort.right_drive', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='excavate', full_name='RobotEffort.excavate', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deposit', full_name='RobotEffort.deposit', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='should_reset', full_name='RobotEffort.should_reset', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='led_color', full_name='RobotEffort.led_color', index=6,
      number=7, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=481,
)

DESCRIPTOR.message_types_by_name['RobotSensors'] = _ROBOTSENSORS
DESCRIPTOR.message_types_by_name['RobotEffort'] = _ROBOTEFFORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotSensors = _reflection.GeneratedProtocolMessageType('RobotSensors', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTSENSORS,
  '__module__' : 'RobotMsgs_pb2'
  # @@protoc_insertion_point(class_scope:RobotSensors)
  })
_sym_db.RegisterMessage(RobotSensors)

RobotEffort = _reflection.GeneratedProtocolMessageType('RobotEffort', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTEFFORT,
  '__module__' : 'RobotMsgs_pb2'
  # @@protoc_insertion_point(class_scope:RobotEffort)
  })
_sym_db.RegisterMessage(RobotEffort)


# @@protoc_insertion_point(module_scope)
