name: Light Continuous Integration Tests

on:
  push:

jobs:
  run-build:
    name: Make sure the code builds
    needs: build-container
    runs-on: ubuntu-latest
    container: ghcr.io/purduelunabotics/development:latest

    steps:
      - name: Install any new deps
        run: rosdep install -r --from-paths /luna_ws/src --ignore-src --rosdistro jazzy -y --skip-keys="ros_gz_bridge ros_gz_sim"
      - name: Test building
        shell: bash
        run: cd /luna_ws/ && source /opt/ros/jazzy/setup.bash && colcon build
