name: Light Continuous Integration Tests

on:
  push:

jobs:
  run-build:
    name: Make sure the code builds
    runs-on: ubuntu-latest
    container: ghcr.io/purduelunabotics/development:latest

    steps:
      - name: Pull code
        shell: bash
        run: cd /luna_ws/src/purdue_lunabotics && git fetch && git checkout ${{ github.sha }}
      - name: Install any new deps
        shell: bash
        run: rosdep install -r --from-paths /luna_ws/src --ignore-src --rosdistro jazzy -y
      - name: Test building
        shell: bash
        run: cd /luna_ws/ && colcon build
